### ISSUE TITLE
Move Recording time and station fields

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/clevmetro-nfd#123]
Move Recording time and station fields under "Observation Recorder" instead of "Observation"

**Comment by ricardogsilva** [comment]
This seems like a simple task, but indeed it is not.

The way form fields are currently laid out in the various tabs for the UI is dependent on their underlying models. 
So, the `Observation` fontend tab only has form fields from the `models.OccurrenceObservation` model, the `Observer` tab only has form fields from the `models.PointOfContact` model, and so on.

This means that in order to comply with the requirements of this issue I'll have to do some substantial changes to the code because the way that the formitems is rendered is currently not flexible enough.

**Comment by giohappy** [comment]
what if we move the model fields around?

**Comment by ricardogsilva** [comment]
In this case that will only move the problem elsewhere, since the `Observation Recorder` UI tab is showing attributes from the `models.PointOfContact` model and the `Observation Verifier` and `Observer` also show attributes from the same model. We'd get `recording_station` and `recording_datetime` under all those UI tabs.
