### ISSUE TITLE
For Land animal move 'marks' from "Details" to "Location".

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/clevmetro-nfd#128]

**Comment by ricardogsilva** [comment]
For similar reasons to the explanation in https://github.com/geosolutions-it/clevmetro-nfd/issues/123#issuecomment-365658872, it is not simple to satisfy this issue without a substantial refactor of the way by which the forms are generated.

In this case, since `marks` is an attribute of the `models.Details` model it is not easily transferable to the UI's `Location` tab. And even if we switched the field around in the database and make `marks` an attribute of the `Location` model, that would mean that all `OccurrenceTaxon` instances would suddently have a `marks` form field showing up on their `Location` UI form including other types of animals, plants, etc.

**Comment by giohappy** [comment]
I see the problem. The "clean" solution would be to create a further derived Location and Detail classes for animals...
I don't like it but I guess some hardcoded client side switches would be faster.
